---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

trigger:
  branch:
  - master

steps:
- name: docker
  image: plugins/docker
  settings:
    repo: docker.io/kanatakita/dumper
    tags: latest
    dockerfile: ./Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

